### ISSUE TITLE
Following steps from the README isn't enough to get this running

### ISSUE THREAD

**Issue by chocolatereign** [auth0/nginx-jwt#21]
Hey there,

Sorry in advance if this is a basic issue :smile:

I am trying to make use of your work to accept jwt authentication through nginx, and following your README wasn't enough to get it up and running.  I believe I have configured everything correctly, but your script seems to fail immediately.  Is there a step that might be missing?

Here is my `nginx.conf`:
http://p.ngx.cc/66

Here is the exception:

```
2015/05/26 19:38:21 [error] 24367#0: *12 lua entry thread aborted: runtime error: /home/ubuntu/downloads/nginx-jwt.lua:1: loop or previous error loading module 'resty.jwt'
stack traceback:
coroutine 0:
        [C]: in function 'require'
        access_by_lua(nginx.conf:16):2: in function <access_by_lua(nginx.conf:16):1>, client: y.y.y.y, server: , request: "GET / HTTP/1.1", host: "x.x.x.x:8080"
~
```

Thanks!

**Comment by twistedstream** [comment]
@chocolatereign We had yet to merge the final PR so you weren't running against all the latest code.  Now we finally have!

Can you try running through the latest README and if you have the same issue, perhaps reopen this issue; or if you encounter something new, create a new issue?

Also, the error you show seems to indicate an issue with the [HttpLuaModule](http://wiki.nginx.org/HttpLuaModule) itself.  Make sure you're using an [openresty](http://openresty.org/) distribution of Nginx.  If not, your mileage may vary as we've really only tested this library against openresty.  Alternatively you could try running your `nginx.conf` in your own Docker container as we're doing with the containers created in the tests for this library.
