### ISSUE TITLE
./build deps fails on ubuntu

### ISSUE THREAD

**Issue by chocolatereign** [auth0/nginx-jwt#22]
Hey there,

I just cloned the repo to my Ubuntu EC2 instance and ran `sudo ./build deps`, as outlined in the README.  This returns the following error:

`./build: 3: set: Illegal option -o pipefail`

**Comment by chocolatereign** [comment]
FYI, it seems to be resolved by removing the `#!/bin/sh` reference at the top, and changing all instances of `sh` to `bash`.

**Comment by twistedstream** [comment]
So the build steps were only really tested on Mac OS but it would be ideal to see them work on Ubuntu, especially given the use of Docker.  I'll test and see if your proposed change continues to work on my Mac and implement them if everything works!

**Comment by twistedstream** [comment]
@chocolatereign Please try it now.  I was able to get `./build deps` to work both on my Mac and on an Ubuntu VM.
