### ISSUE TITLE
Unable to find resty.jwt

### ISSUE THREAD

**Issue by zentraedi** [auth0/nginx-jwt#29]
Hi folks!

I tried to install nginx-jwt but i'm getting this error:

```
2015/07/23 12:06:05 [error] 3622#3622: *5 lua entry thread aborted: runtime error: access_by_lua(staging.eazycoin.com:16):2: loop or previous error loading module 'nginx-jwt'
stack traceback:
coroutine 0:
    [C]: in function 'require'
    access_by_lua(xxxxx.xxxxx.com:16):2: in function <access_by_lua(xxxxx.xxxxx.com:16):1>, client: 192.168.2.31, server: staging.eazycoin.com, request: "POST / HTTP/1.0", host: "192.168.2.33"
```

Specifically nginx-jwt can't seem to find: "resty.jwt"

I have everything under: /etc/nginx/lua

in my vhost config file i have:

```
lua_package_path '/etc/nginx/lua/?.lua;;';

server {
...
    location / {
        access_by_lua '
            local jwt = require("nginx-jwt")
            jwt.auth()
        ';
    }
...
}
```

I appreciate any help you guys can offer, thanks in advance.

**Comment by andrew-jones** [comment]
I was getting the same error.  It's something to do with the adding to the lua scripts path.  I got around it by copying the files into openresty's lualib directory.

Here's a working RUN command from my Dockerfile

```
RUN wget -O nginx-jwt-master.zip https://github.com/auth0/nginx-jwt/archive/master.zip \
  && unzip nginx-jwt-master \
  && rm -fr nginx-jwt-master.zip \
  && cd nginx-jwt-master \
  && ./build deps \
  && cp -fr *.lua /usr/local/openresty/lualib \
  && cp -fr lib/* /usr/local/openresty/lualib \
  && rm -fr ../nginx-jwt-master
```

**Comment by zentraedi** [comment]
Thanks @andrew-jones, i'll try that.

**Comment by twistedstream** [comment]
@zentraedi @andrew-jones I'm seeing the same error as I test on Ubuntu. I'll take a closer look as this was working fine at one point in time...

**Comment by twistedstream** [comment]
I believe I have a fix for this that will roll into into PR #31. I need to first get the project migrated from Boot2Docker to Docker Toolbox so I can properly test on the Mac, which I'm doing with #35.

**Comment by zentraedi** [comment]
Thanks @twistedstream. Actually i was trying to set it up on Debian. I'll give it a shot again when it's done.

Thanks.

**Comment by digitalogical** [comment]
Same problem here, needed to add the openresty lualib folder to the lua_package_path.
`lua_package_path "/usr/local/nginx-jwt/?.lua;/usr/local/openresty/lualib/?.lua;;";`
