### ISSUE TITLE
Token verification doesn't include expiry check

### ISSUE THREAD

**Issue by rubyboy** [auth0/nginx-jwt#30]
The verify method lets you specify leeway for the expiry check. If you don't specify one then there is no expiry check at all, which means it lets expired tokens go through.
The fix should be to add a leeway (at least specify 0 for a default of no leeway).
There's a fork I've created with this fix, but it includes other enhancements as well - I'll create a pull request separately, but if you want to fix this issue all that's needed is to add the parameter 0 to the "verify" call.

**Comment by bobrik** [comment]
It should work now: https://github.com/SkyLothar/lua-resty-jwt/commit/480f17dbb557180b513420563dd8ccdc0cef62cc

**Comment by rubyboy** [comment]
Thanks for that. Looks good!
We're currently using our own fork. At some point I'll merge and make sure it's consistent with the master branch.
