### ISSUE TITLE
Support validation with asymmetric keys

### ISSUE THREAD

**Issue by twistedstream** [auth0/nginx-jwt#41]
As noted in the [Configuration](https://github.com/auth0/nginx-jwt#configuration) section of the README, `nginx-jwt` only supports symmetric keys for validating JWT's. However, many applications require the use of asymmetric keys so they don't have to distribute secrets (which can be used to sign JWT's) to all of their applications.

To implement asymmetric keys, `nginx-jwt` would need to support the `RS256` encryption algorithm, which really means the underlying JWT library [lua-resty-jwt](https://github.com/SkyLothar/lua-resty-jwt) would need to support it. That library has recently added limited support for `RS256`, but only if your JWT also supplies the [`x5c` header](https://tools.ietf.org/html/draft-ietf-jose-json-web-key-41#section-4.7). While this approach works, one drawback is that header contains the public key itself, which adds a noticeable increase to the JWT's size. Usually the `x5c` header needs to contain the entire cert trust chain (significantly more size) but `lua-resty-jwt` library relieves this by requiring the existence of a `trusted_certs_file` that must be deployed to the server, so that the `x5c` header only contains the signing cert itself.

It's my opinion that most users of `RS256` would prefer to use an approach where the public key was somehow provided externally to the JWT. Here are a couple ideas, but they would both require changes to the underlying `lua-resty-jwt` library to support them:
1. Put both the signing certificate and chain trust certs in the `trusted_certs_file` and not use the `x5c` header. However, I'm not entire sure this follows the spec.
2. Use the [`kid` header](https://tools.ietf.org/html/draft-ietf-jose-json-web-key-41#section-4.5) (Key ID) to point to a public key on some trusted external public key server. We'd need additional configuration to support how that certificate would be obtained (i.e. an HTTP call to download it, and maybe cache it on the first request). We also need to figure out if it would be `lua-resty-jwt` or `nginx-jwt` that would do the work of obtaining that cert.

**Comment by twistedstream** [comment]
Well, this may be the shortest-lived enhancement request ever. It turns out `nginx-jwt` does have support for asymmetric keys as of PR #38. I didn't pay attention to that PR close enough nor did I read the source for [lua-resty-jwt](https://github.com/SkyLothar/lua-resty-jwt) close enough as [its clear](https://github.com/SkyLothar/lua-resty-jwt/blob/master/lib/resty/jwt.lua#L193-L199) you can pass the public key cert via the `secret` argument.

What I need to do now is add some tests that prove you can use asymmetric keys.  A PR will be forthcoming.

For the moment, I don't see a need to do anything fancier, so I'm going to close this issue.  Further comments are welcomed.

**Comment by ghost** [comment]
If one was to only configure the JWT_SECRET with a public key, it might a bit of a surprise to find out that the server would accept a JWT signed by the public key with the HS256 algorithm, as described in the auth0 blog[1].

Perhaps as a minimum, one could configure JWT_SECRET with a public key AND configure the the `lua-resty-jwt` whitelist with only asymmetric algorithms?

[1] https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
