### ISSUE TITLE
Trouble finding 'resty.jwt'

### ISSUE THREAD

**Issue by knguyen2525** [auth0/nginx-jwt#55]
Hello,

Having some trouble with these statements:

```
local jwt = require("nginx-jwt")
jwt.auth()
```

Looks like it can find 'nginx-jwt.lua' just fine but it's having trouble finding 'resty.jwt'. I also can't find this file anywhere.

Any ideas?
Thanks

**Comment by nkijak** [comment]
@knguyen2525 what's your lua_package_path set to?  The README isn't clear but you need a wild 
card, here's mine, your paths may be different:     
```
lua_package_path "/opt/nginx-jwt/?.lua;;";
```

**Comment by knguyen2525** [comment]
Thanks, that did the trick.
