### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by tarekrached** [auth0/nginx-jwt#70]
I'm seeing the last commit to master 18 months ago on Nov 13, 2015, [2 year old open PRs](https://github.com/auth0/nginx-jwt/pull/28), and a bunch of open Issues.

Should we switch to the [platinummonkey fork](https://github.com/platinummonkey/nginx-jwt)?

@twistedstream any insight as to what the path forward is here?

**Comment by pieterlange** [comment]
At this point i think we can conclude this project is dead/abandonware and thus not safe for use.

pinging some people who are still active on the auth0 github org...

@mpaktiti @khorne3 @jeffreylees @luisrudge @jerriep @aaguiarz

**Comment by luisrudge** [comment]
hey @pieterlange I'm on holidays until Wednesday, but I'll ping someone internally about this project. I see that the fork mentioned also has stopped development (latest commit in 2016). Is that because it is considered stable and done (as in, no more features needed)?

**Comment by aaguiarz** [comment]
Hi @pieterlange / @tarekrached,

Auth0 will not be maintaining this repository for the time being, so we'll archive it.

I apologize for the delay answering and the inconveniences. 

Andres
Product Manager @ Auth0
