### ISSUE TITLE
Secure a URL by transmitting an auth cookie

### ISSUE THREAD

**Issue by twistedstream** [auth0/nginx-jwt#9]
Instead of requiring the JWT in the `Authorization` request header.  This will enable securing of a website (vs. a web API).

The workflow for this feature would look something like this:
- If a URL is configured to be secured, then an incoming request must contain a valid auth cookie.
- If it's missing, the module will respond with a `302` redirect, pointing to the configured Auth0 login page.
- When the user performs a valid login at the page, they are redirected back to the Nginx server
- The module will extract the JWT from Auth0 and generate an auth cookie (which probably just contains the JWT) and then perform the initial proxied request to the backing URL, returning the new cookie back to the browser
- The browser will store the cookie and continue to use it for subsequent requests

**Comment by twistedstream** [comment]
Per #11, this issue will ultimately end up in a new project

**Comment by soichih** [comment]
+1 .. although this is already closed..

I have our own authentication service that generates JWT (for web apps) and if nginx-jwt can made to deal with JWT token stored in cookie, it will be able to authenticate just about any web app served under nginx-jwt. 

Is there a nginx script that does this already?
